### ISSUE TITLE
The KML tracker problem

### ISSUE THREAD

**Issue by g8dhe** [rossengeorgiev/habitat-mobile-tracker#69]
The KML tracker file isn't showing the "current" position for the balloon icon rather a previous position, possibly first heard ?
http://360.g8dhe.net/hab_flights/2015_Flights/Capture2.JPG  the Icon position is shown as @ 18:22:39 two days previous 2015-03-09 rather than the current position @ 2015-03-11 10:34:00
Here is the plotted results;
http://360.g8dhe.net/HAB_Flights/2015_Flights/EDUPICDX1_20150311/EDUPICDX1_201503111036.jpg

**Comment by rossengeorgiev** [comment]
The bug should be fixed. Thanks

**Comment by g8dhe** [comment]
YUp looking good now many thanks!
