### ISSUE TITLE
Left hand #main bar doesn't appear

### ISSUE THREAD

**Issue by richardeoin** [rossengeorgiev/habitat-mobile-tracker#71]
In latest Firefox (37.0.1) on Mint the left-hand bar doesn't appear at certain screen resolutions. This can be replicated by zooming in and out.

On some resolutions, the calculation will be off by one pixel so both boxes won't fit on the screen width. Maybe rework html to fix this, or a kludge in checkSize()

**Comment by rossengeorgiev** [comment]
This will be best solved by reworking the html layout, and cleaning/removing the JS code.

**Comment by rossengeorgiev** [comment]
fixed in 5de3664cdac50da4b14606f263366ffc69cbe88a

**Comment by rossengeorgiev** [comment]
This may still happen on Chrome on Windows 7
