### ISSUE TITLE
Google Earth file broken

### ISSUE THREAD

**Issue by g8dhe** [rossengeorgiev/habitat-mobile-tracker#74]
This was working yesterday 24th April, but is broken today, situation has changed at various times durig the day, possibly corrupted input data from APRS records ???
Yes KC2DIJ-1 is the cause of the problem - exclude that record and all is well

**Comment by rossengeorgiev** [comment]
Yep, KC2DIJ-1 had control chars in the comment field, which apparently breaks GE. Anyway, it's fixed now.
