### ISSUE TITLE
Transfer location to predict.habhub.org ?

### ISSUE THREAD

**Issue by g8dhe** [rossengeorgiev/habitat-mobile-tracker#82]
Would it be possible to arrange for lat/long/alt to be transferred (right click or whatever) to a new page on the predict.habhub.org so that a prediction from current position can be obtained ?

**Comment by rossengeorgiev** [comment]
The tracker already automatically runs a prediction for every balloon (except the ones that have hysplit). I don't see the point of being able to run one manually.

**Comment by g8dhe** [comment]
The parameters aren't always the right ones for a given balloon, sometimes it helps to run predictions for several different times during the launch phase and a KML version is also available to save or show in GE etc.

**Comment by rossengeorgiev** [comment]
You can click on the path close to the current position which will bring a popup window. The parameters can be copied one by one from there.

**Comment by g8dhe** [comment]
OK not critical I guess.
