### ISSUE TITLE
Payload selection doesn't work

### ISSUE THREAD

**Issue by G8KNN** [rossengeorgiev/habitat-mobile-tracker#85]
Clicking on a payload in the left hand pane doesn't select the payload.    I've only seen this issue on Chrome (51.0.2704.106) running under Linux Mint (17.3).  Firefox works fine.    Chrome works fine under Windows 10.

I think this may have first appeared about the same time as the full-screen button first appeared on the map a few weeks ago  

I noticed that Babs mentioned this on IRC yesterday, so I'm not the only one :-)

**Comment by rossengeorgiev** [comment]
Can't replicate. Everything works for me under Linux on Chrome 51

**Comment by G8KNN** [comment]
Update: If I touch on the payload via touchscreen the payload selects OK, but a touchpad or mouse click just doesn't work  :-(

**Comment by thasti** [comment]
I can confirm this issue - selection via laptop touchpad does not work, however touchscreen input works fine. No problems in Firefox. Setup: Chromium 52, Arch Linux on a Lenovo X240.

**Comment by rossengeorgiev** [comment]
Just to confirm, it's only in chrome that touchpad and mouse clicks don't work?

**Comment by thasti** [comment]
Correct, Firefox is OK with both, Crome only accepts touchscreen taps for payload selection, mouse clicks are ignored. 
Starts to work again when Touch-Events are manually disabled using chrome://flags

**Comment by rossengeorgiev** [comment]
The issue appears in Chrome 52 on Windows 10. Will look into it

**Comment by rossengeorgiev** [comment]
The issue seems to be webkit specific, so Chrome and Opera are affected. Expanding/collapsing should work now including the buttons.

Can you guys confirm that it works on linux chrome?

Note that drag scrolling won't work on Chrome, only scrollwheel.

**Comment by thasti** [comment]
Hmh, expand/collapse does indeed work using the mouse now, but now using the touchscreen for payload selection doesn't work anymore. All other features seem to work nicely using the touchscreen.

However, drag scrolling works as well as it does using the scrollwheel. Is there anything we can contribute to help you fix the problem?

**Comment by G8KNN** [comment]
Also confirm that mouse/trackpad now selects the payload OK and the buttons also work.   The touchscreen doesn't work though.

**Comment by rossengeorgiev** [comment]
Can you guys verify that touchscreen, mouse and drag scrolling works ?

**Comment by G8KNN** [comment]
Yup, they all work!

thanks

**Comment by thasti** [comment]
Can also confirm, thanks! Keep up the great work!

**Comment by rossengeorgiev** [comment]
Thanks for the help guys.
