### ISSUE TITLE
Know which balloon belongs to which range rings (feauture request)

### ISSUE THREAD

**Issue by zanco** [rossengeorgiev/habitat-mobile-tracker#86]
At the moment of a lot of activity it is not possible to see to which payload a range ring belongs.

It would be nice if that was possible in the feauture.

**Comment by rossengeorgiev** [comment]
Have you tried the `Highlight selected vehicle` from the settings page? When you turn it on, only the selected balloon will be visible.

**Comment by zanco** [comment]
No, I did not until 2 minutes ago. That solves my question, thanks for the fast reply.

**Comment by rossengeorgiev** [comment]
No worries :smile:
