### ISSUE TITLE
tracker is no longer updating UBSEDS18 position

### ISSUE THREAD

**Issue by zanco** [rossengeorgiev/habitat-mobile-tracker#87]
UT3BW is still receiving the UBSEDS18 but since over one hour the position does not get updated. He asks is anyone can look at it.

Edit: the parsers log shows no flights are updated at all at the moment

Edit: 10:15 UTC all seems to work okay again !

Thanks,

Ben

**Comment by rossengeorgiev** [comment]
Yeah, there were some issues with some recent changes. It was fixed. Anyway thanks for the report. :+1:
