### ISSUE TITLE
Embed code

### ISSUE THREAD

**Issue by g8dhe** [rossengeorgiev/habitat-mobile-tracker#88]
The default duration appears to be the "ALL" setting, this gets rather long at times and can slow some browsers down.  Would it be possible to change the default or provide an option to alter the setting to one of the standard ones in the main code ?

**Comment by rossengeorgiev** [comment]
I've noticed that it takes a while to load due to number of flight, and especially the ones that are floating for long periods. I think changing the period to `1 day` should be sufficient to resolve the issue.

**Comment by g8dhe** [comment]
Yup, that would be fine for now set at 1 day.  
Would having the ability to set the default in the preview window, be of assistance in the future if things change yet again with further developments ?

**Comment by g8dhe** [comment]
Just realised that whilst the preview shows the default of 1 day the actual embed code still results in the "ALL" parameter being selected by default :-(
