### ISSUE TITLE
request: block habitat data from my callsign from the parser logtail

### ISSUE THREAD

**Issue by zanco** [rossengeorgiev/habitat-mobile-tracker#89]
Hi. I have a SSDV transmission running with 100 mW at 27 meter ASL. I transmit one 1280 \* 720 image every hour. In between the tracker sends GPS data and callsign which are added to log but they are not interesting info because my location is fixed. Sometimes that lot of data annoys other people if they try to find something in the log.

Could it be possible to block the messages if my callsign is in it ?

There is an option in the lora-gateway software to disable the habitat upload but some of my receiving stations around forget to disable it after tracking a HAB.

I am open for other kinds of solutions also

Thanks,
Ben

**Comment by rossengeorgiev** [comment]
Sorry for the late response, but that's not possible at the moment.
