### ISSUE TITLE
Embed code was #88 but closed

### ISSUE THREAD

**Issue by g8dhe** [rossengeorgiev/habitat-mobile-tracker#90]
Just realised that whilst the preview shows the default of 1 day the actual embed code still results in the "ALL" parameter being selected by default :-(

**Comment by rossengeorgiev** [comment]
Yes. It is assumed that embed code will be used to show up one or more balloons on your own site. You would want the full flight path, right? So, it does it by default.

You could just remove the `embed=1` bit and it should give you the behavior you are looking for.

**Comment by g8dhe** [comment]
Right yes, just want to show current flights without a massive download of data each time.
