### ISSUE TITLE
inconsistent times observed on left bar and on track/prediction

### ISSUE THREAD

**Issue by dbrooke** [rossengeorgiev/habitat-mobile-tracker#92]
Firefox 50.0.2 on Linux

Not really sure if this is an issue with the tracker or the server/database but since I observed it in the tracker thought I'd best raise it here.

I first noticed that the predicted landing time for the Nikon payload was not far enough in the future and then that clicking on the track line on recent uploads also showed an incorrect time stamp, some minutes in the past but consistent with the error for the landing time.

This can also be seen on the left bar in the screen capture where I also observed that the last time stamp for BDBC7 had an error in the opposite direction (I was the final receiver and the received 1h 4m ago appears correct but I don't recall if the time error was present at the time of upload).

The clock in upper right shows correct time and the time stamp for SHOGUN_chase appears to be correct.

Others observed similar issues, see
http://habhub.org/zeusbot/logs/highaltitude.log.20161204
from 17:56 to 18:01

![2016-12-04-174935_1918x1183_scrot](https://cloud.githubusercontent.com/assets/1096693/20868374/099c81ac-ba52-11e6-980f-ebef353ec436.png)

**Comment by rossengeorgiev** [comment]
The displayed DATETIME on the left is the one reported by the payload. It is possible that the payload lost GPS and reported a stale timestamp. `Received X ago` is the time since the server got a report from the payload.

**Comment by dbrooke** [comment]
Thanks for the explanation. For BDBC7 I found a matching corrupt sentence in my log. That payload was using an XOR checksum which passed despite the corruption. I didn't receive the Nikon payload myself so can't explain that one.

**Comment by rossengeorgiev** [comment]
XOR checksum? I'm confused is that a parity byte, or something else? Party byte is not a great way to ensure integrity. Either way, looking at both sentences and calculating the checksum should tell you what happened.

**Comment by dbrooke** [comment]
I believe it's just a parity byte generated by XORing successive bytes in the message and agree that it's insufficient protection for RTTY but that's what the payload (not mine) was sending. I just happened to receive and upload a sentence where the check passed despite the corruption.
